services:
  selenium:
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
      - 7900:7900
    restart: always
  scraper:
    build: ./scraper 
    env_file:
     - stack.env
    volumes:
      - /etc/localtime:/etc/localtime
    depends_on:
      - selenium
    restart: always
  api:
    build: ./api
    env_file:
     - stack.env
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - 5863:5863
    restart: always

      